require 'colorize'
require 'rubygems'
require 'byebug'
require 'pp'

require './core_ext/array.rb'

require './implement/action.rb'
require './implement/city.rb'
require './implement/player.rb'
require './implement/proposition.rb'
require './implement/tech.rb'
require './implement/tile.rb'
require './implement/unit.rb'
require './implement.rb'

require './rules/civplicity.rb'
require './rules/combat.rb'
require './rules/culture.rb'
require './rules/diplomacy.rb'
require './rules/production.rb'
require './rules/research.rb'
require './rules/world.rb'
require './rules/known_world.rb'

